# Generated by Django 3.2.5 on 2021-07-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210714_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_accounts_profile_friends_+', to='accounts.Profile'),
        ),
    ]
