# Generated by Django 3.2.5 on 2021-07-16 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reviews',
        ),
    ]
