# Generated by Django 3.2.5 on 2021-07-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20210716_2312'),
        ('accounts', '0009_profile_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reviews',
        ),
        migrations.AddField(
            model_name='profile',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='reviews.Review'),
        ),
    ]
