# Generated by Django 3.2.5 on 2021-07-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='game',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
