# Generated by Django 3.2.5 on 2021-07-17 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20210713_1942'),
        ('reviews', '0010_auto_20210716_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='games.game'),
        ),
    ]
