# Generated by Django 3.2.5 on 2021-07-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('screenshot', models.ImageField(upload_to='games')),
                ('description', models.TextField()),
            ],
        ),
    ]
