# Generated by Django 3.2.5 on 2021-07-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='screenshot',
        ),
    ]
