# Generated by Django 3.2.5 on 2021-07-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210709_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='game',
            name='platforms',
        ),
    ]
