# Generated by Django 3.2.5 on 2021-07-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20210709_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='released',
        ),
    ]
