# Generated by Django 3.2.5 on 2021-07-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='background_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_owned',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
