# Generated by Django 3.2.5 on 2021-07-09 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0007_auto_20210709_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='play_status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'Completed'), ('PLAYING', 'Playing'), ('UNSTARTED', 'Unstarted')], default='UNSTARTED', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('background_image', models.URLField(blank=True, null=True)),
                ('is_owned', models.BooleanField(blank=True, default=False, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
