# Generated by Django 3.2.5 on 2021-07-09 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20210709_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
