# Generated by Django 3.2.5 on 2021-07-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_game_play_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='play_status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'Completed'), ('PLAYING', 'Playing'), ('UNSTARTED', 'Unstarted')], default='UNSTARTED', max_length=15, null=True),
        ),
    ]
