# Generated by Django 3.2.5 on 2021-07-19 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0014_alter_game_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='owner',
        ),
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
