# Generated by Django 3.2.5 on 2021-07-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_alter_game_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='release_date',
            new_name='released',
        ),
    ]
